package com.sentimentanalysis.project.domain.enumeration;

/**
 * The Countrylist enumeration.
 */
public enum Countrylist {
    ARGENTINA, ALGERIA, ANGOLA, BELGIUM, BOTSWANA, BRAZIL, CAMEROON, CANADA, CHINA, EGYPYT, ETHOPIA, FRANCE, GABON, GERMANY, GHANA, ISRAEL, ITALY, JAMAICA, JAPAN, KENYA, LESOTHO, LIBERIA, LIBYA, MALI, MAURITIUS, MEXICO, MOROCCO, MOZAMBIQUE, NAMIBIA, NETHERLANDS, NIGER, NIGERIA, PARAGUAY, PHILIPPINES, PORTUGAL, RUSSIA, RWANDA, SAUDI_ARABIA, SENEGAL, SOMALIA, SOUTH_AFRICA, SPAIN, SWAZILAND, SWEDEN, SWITZERLAND, TANZANIA, TUNISIA, UGANDA, UNITED_KINGDOM, VENEZUAL, YEMEN, ZAMBIA, ZIMBWAWE
}
